apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-docker-crypto-task-deployment
  labels:
    app: k8s-docker-crypto-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-docker-crypto-task
  template:
    metadata:
      labels:
        app: k8s-docker-crypto-task
    spec:
      containers:
      - name: k8s-docker-crypto-task
        image: kriach/crypto-advisor-task
        ports:
        - containerPort: 80